### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by freephile** [jdlrobson/skins.wmflabs.org#6]
The background color choice is a bit.... or maybe you could say a lot... weird.

In order to make skin selection a more 'polished' and 'professional' experience, could you make the background less "in your face" so that the content itself can attract the viewer's attention. I would say any neutral color could work, but probably the best is to choose either white, or black -- and maybe a switch to be able to go from 'light' mode to 'dark' mode.

Thanks

**Comment by RheingoldRiver** [comment]
This might work a bit better than the current theme:

```css
body {
  background:white!important;
  color:black;
}

.snapshot img {
  border: 1px solid #E80447;
}
```

Also, this makes it a bit cleaner too, plus helps you see what labels are attached to what cards:
```css
.snapshot a {
  text-decoration: none;
}

.snapshot:hover a {
  text-decoration: underline;
  text-decoration-style: dotted;
}
```

And that last part can be further helped with:

```css
h3[data-v-1a6a52] {
  padding-bottom:0;
}
```

The ending result:
![image](https://user-images.githubusercontent.com/18037011/114007333-de425380-9826-11eb-8b61-b90914bd229a.png)

**Comment by RheingoldRiver** [comment]
Here's another option:

```css
:root {
  --color:#E80447;
}

.snapshot:hover {
  --color:#F1D800;
}

body {
  background:white!important;
  color:black;
}

.snapshot img {
  padding:1em;
}

.snapshot {
  background-color:var(--color);
  display:flex;
  flex-direction:column;
  align-items:center;
  margin:.5em;
}

img[data-v-1a6a52] {
  background:var(--color);
}

h3[data-v-1a6a52] {
  background-color:var(--color);
  color:white;
  padding-bottom:0;
}

h3 a[data-v-1a6a52] {
  color:white;
}
```

![image](https://user-images.githubusercontent.com/18037011/114009601-e7ccbb00-9828-11eb-81c6-13c877fe6620.png)

**Comment by RheingoldRiver** [comment]
Here's `#eee` as background color:
## Design 1
```css
body {
  background:#eee;
  color:black;
}

.snapshot img {
  border: 1px solid #E80447;
}

.snapshot a {
  text-decoration: none;
}

nav[data-v-16d7b1] a:hover,
.snapshot:hover a {
  text-decoration: underline;
  text-decoration-style: dotted;
}

h3[data-v-1a6a52] {
  padding-bottom:0;
  background:none;
}

nav[data-v-16d7b1] a {
  color: #E80447;
}

nav[data-v-16d7b1] {
  border-color:#E80447;
}
```
![image](https://user-images.githubusercontent.com/18037011/114242932-4f7e2580-9951-11eb-88c3-2530095fe19e.png)

## Design 2
Also I changed the hover to purple instead of the really bright yellow in this one:
```css
:root {
  --color:#E80447;
}

nav a:hover,
.snapshot:hover {
  --color:#C24CBF;
}

body {
  background:#eee;
  color:black;
}

.snapshot a {
  text-decoration: none;
}

nav[data-v-16d7b1] a:hover,
.snapshot:hover a {
  text-decoration: underline;
  text-decoration-style: dotted;
}

.snapshot img {
  padding:1em;
}

.snapshot {
  background-color:var(--color);
  display:flex;
  flex-direction:column;
  align-items:center;
  margin:.5em;
}

img[data-v-1a6a52] {
  background:var(--color);
}

h3[data-v-1a6a52] {
  background-color:var(--color);
  color:white;
  padding-bottom:0;
}

h3 a[data-v-1a6a52] {
  color:white;
}

nav[data-v-16d7b1] a {
  color: var(--color);
}

nav[data-v-16d7b1] {
  border-color:#E80447;
}
```
![image](https://user-images.githubusercontent.com/18037011/114243190-c7e4e680-9951-11eb-8f74-24bc31d33f44.png)
